const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Timeline,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.Particles,
		C3.Plugins.NinePatch,
		C3.Behaviors.Bullet,
		C3.Behaviors.Timer,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Browser.Acts.SetWarnOnClose,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.NinePatch.Acts.SetPosToObject,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Behaviors.Timer.Exps.TotalTime,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Spritefont2.Acts.SetBoolInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetZElevation,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Particles.Acts.SetTowardPosition,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.System.Exps.imageloadingprogress,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Preload
	];
};
self.C3_JsPropNameTable = [
	{Sine: 0},
	{titlepart1: 0},
	{sky: 0},
	{foreground: 0},
	{sun: 0},
	{Tween: 0},
	{blackness: 0},
	{playbutton: 0},
	{TimelineController: 0},
	{titlepart2: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{Audio: 0},
	{controlsbutton: 0},
	{dirtback: 0},
	{labels: 0},
	{backbutton: 0},
	{cat: 0},
	{pickaxe: 0},
	{rock: 0},
	{rockparticles: 0},
	{miningpopup: 0},
	{star: 0},
	{goldparticles: 0},
	{disappearing: 0},
	{coinhud: 0},
	{coinsdisplay: 0},
	{gemhud: 0},
	{gemsdisplay: 0},
	{crystalhud: 0},
	{crystalsdisplay: 0},
	{background: 0},
	{minipopup: 0},
	{shoparrow: 0},
	{shop: 0},
	{Cost: 0},
	{CostUp: 0},
	{Level: 0},
	{CurrencyName: 0},
	{UpgradeName: 0},
	{UpgradeAmount: 0},
	{RebirthsRequired: 0},
	{DefaultCost: 0},
	{IsPickaxeUpgrade: 0},
	{DoesNotResetOnRebirth: 0},
	{MaxLevel: 0},
	{Description: 0},
	{ObjectToSpawn: 0},
	{catcoinupgradebase: 0},
	{UIDToFollow: 0},
	{ImagePointToFollow: 0},
	{IsPickaxeText: 0},
	{upgradelevel: 0},
	{upgradecost: 0},
	{upgradecosttype: 0},
	{gemupgradebase: 0},
	{crystalupgradebase: 0},
	{pickaxeupgrade: 0},
	{catminerupgrade: 0},
	{dogworkerupgrade: 0},
	{gemdrillerupgrade: 0},
	{gemchancedisplay: 0},
	{crystalchancedisplay: 0},
	{catcoinsperclickdisplay: 0},
	{catcoinsmultiplierdisplay: 0},
	{gemmultiplierdisplay: 0},
	{crystalmultiplierdisplay: 0},
	{greenparticles: 0},
	{greenstar: 0},
	{purpleparticles: 0},
	{purplestar: 0},
	{crystaldrillerupgrade: 0},
	{cattreatsicon: 0},
	{rebirthmenubutton: 0},
	{rebirthbackground: 0},
	{awardbackground: 0},
	{rebirthicon: 0},
	{rebirthparticles: 0},
	{rebirthstar: 0},
	{awardtext: 0},
	{rebirthcatcoincostdisplay: 0},
	{hudicon: 0},
	{rebirthgemcostdisplay: 0},
	{rebirthcrystalcostdisplay: 0},
	{rebirthbutton: 0},
	{clickanywhere: 0},
	{arrow: 0},
	{whiteorb: 0},
	{Bullet: 0},
	{miniwhiteorb: 0},
	{alert: 0},
	{cattreatsshopbutton: 0},
	{cattreatsshopbackground: 0},
	{cattreatsdisplay: 0},
	{cattreatsupgradebase: 0},
	{catcoinmultiplierupgrade: 0},
	{gemmultiplierupgrade: 0},
	{crystalmultiplierupgrade: 0},
	{pickaxeupgradearrow: 0},
	{gempickaxeupgrade: 0},
	{crystalpickaxeupgrade: 0},
	{cattreatsfromrebirthsupgrade: 0},
	{labmenubutton: 0},
	{labbackground: 0},
	{researchmenu: 0},
	{researchicon: 0},
	{researchdisplay: 0},
	{researchmenuarrow: 0},
	{Timer: 0},
	{bigflask: 0},
	{CurrencyToTransfer: 0},
	{transferbutton: 0},
	{catcoinresearchamountdisplay: 0},
	{gemresearchamountdisplay: 0},
	{crystalresearchamountdisplay: 0},
	{researchbarback: 0},
	{researchbar: 0},
	{researchupgradebase: 0},
	{rebirthcountdisplay: 0},
	{Touch: 0},
	{rebirthcattreatsrewarddisplay: 0},
	{supergemdrillerupgrade: 0},
	{holdclickupgrade: 0},
	{supercrystaldrillerupgrade: 0},
	{researchpickaxeupgrade: 0},
	{gemfabricatorupgrade: 0},
	{loadingbarback: 0},
	{loadingbar: 0},
	{loadingtext: 0},
	{loadingpercentagetext: 0},
	{loadingbackground: 0},
	{diamondhud: 0},
	{diamondchancedisplay: 0},
	{diamondmultiplierdisplay: 0},
	{diamonddisplay: 0},
	{diamondupgradebase: 0},
	{blueparticles: 0},
	{bluestar: 0},
	{diamondpickaxeupgrade: 0},
	{rebirthdiamondcostdisplay: 0},
	{diamondmultiplierupgrade: 0},
	{minicatminer: 0},
	{whitestar: 0},
	{snowstorm: 0},
	{disappearparticles: 0},
	{minicatgemdriller: 0},
	{minicatcrystaldriller: 0},
	{tooltip: 0},
	{tooltiparrow: 0},
	{diamondchanceupgrade: 0},
	{superdiamondchanceupgrade: 0},
	{descriptionText: 0},
	{midground: 0},
	{dogworker: 0},
	{crystalrefineryupgrade: 0},
	{kittenquarryupgrade: 0},
	{kittenquarry: 0},
	{pickaxemenubutton: 0},
	{pickaxemenubackground: 0},
	{Type: 0},
	{pickaxedisplay: 0},
	{pickaxeselectarrow: 0},
	{pickaxematerialdisplay: 0},
	{buypickaxebutton: 0},
	{pickaxecosthud: 0},
	{pickaxecostdisplay: 0},
	{bigpickaxe: 0},
	{researchspeedupgrade: 0},
	{shippingicon: 0},
	{shippingbackground: 0},
	{aspectratiofixer: 0},
	{viewcodebutton: 0},
	{Browser: 0},
	{Upgrades: 0},
	{CatcoinUpgrades: 0},
	{GemUpgrades: 0},
	{CrystalUpgrades: 0},
	{UpgradeLabels: 0},
	{Buttons: 0},
	{CatTreatsUpgrades: 0},
	{ResearchUpgrades: 0},
	{DiamondUpgrades: 0},
	{EndGroundY: 0},
	{StartGroundY: 0},
	{EndTitleWidth: 0},
	{EndTitleHeight: 0},
	{StartSunY: 0},
	{EndSunY: 0},
	{IsOnMobile: 0},
	{Volume: 0},
	{PickaxeTier: 0},
	{SelectedPickaxeTier: 0},
	{CatCoins: 0},
	{Gems: 0},
	{Crystals: 0},
	{GemChance: 0},
	{CrystalChance: 0},
	{CatcoinsPerClick: 0},
	{IsInShop: 0},
	{CanClick: 0},
	{CatcoinMultiplier: 0},
	{GemMultiplier: 0},
	{CrystalMultiplier: 0},
	{CatcoinsPerSecond: 0},
	{CatcoinsPerSecondAmount: 0},
	{CatcoinsPerSecondDelay: 0},
	{MaxCatcoinsPerSecond: 0},
	{GemsPerSecond: 0},
	{GemsPerSecondAmount: 0},
	{GemsPerSecondDelay: 0},
	{MaxGemsPerSecond: 0},
	{CrystalsPerSecond: 0},
	{CrystalsPerSecondAmount: 0},
	{CrystalsPerSecondDelay: 0},
	{MaxCrystalsPerSecond: 0},
	{RebirthCount: 0},
	{CatcoinRebirthCost: 0},
	{GemRebirthCost: 0},
	{CrystalRebirthCost: 0},
	{CatTreats: 0},
	{CatTreatsPerRebirth: 0},
	{IsInRebirthMenu: 0},
	{IsRebirthing: 0},
	{IsInCatTreatsShop: 0},
	{IsInLab: 0},
	{IsInPickaxeMenu: 0},
	{IsInResearchMenu: 0},
	{Research: 0},
	{CatcoinsResearchAmount: 0},
	{GemsResearchAmount: 0},
	{CrystalsResearchAmount: 0},
	{ResearchTime: 0},
	{CanHoldToClick: 0},
	{QuedResearches: 0},
	{Diamonds: 0},
	{DiamondChance: 0},
	{DiamondMultiplier: 0},
	{DiamondsRebirthCost: 0},
	{SecretChain: 0},
	{IsDoneRebirthing: 0},
	{CanBuyUpgrade: 0},
	{IsShowingNewPickaxe: 0},
	{IsShippingUnlocked: 0},
	{IsInShippingMinigame: 0},
	{SetState: 0},
	{InputNumber: 0},
	{TimeWaiting: 0},
	{SetValue: 0}
];

self.InstanceType = {
	titlepart1: class extends self.ISpriteInstance {},
	sky: class extends self.ISpriteInstance {},
	foreground: class extends self.ITiledBackgroundInstance {},
	sun: class extends self.ISpriteInstance {},
	blackness: class extends self.ISpriteInstance {},
	playbutton: class extends self.ISpriteInstance {},
	TimelineController: class extends self.IInstance {},
	titlepart2: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	controlsbutton: class extends self.ISpriteInstance {},
	dirtback: class extends self.ISpriteInstance {},
	labels: class extends self.ISpriteFontInstance {},
	backbutton: class extends self.ISpriteInstance {},
	cat: class extends self.ISpriteInstance {},
	pickaxe: class extends self.ISpriteInstance {},
	rock: class extends self.ISpriteInstance {},
	rockparticles: class extends self.IParticlesInstance {},
	miningpopup: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	goldparticles: class extends self.IParticlesInstance {},
	disappearing: class extends self.ISpriteInstance {},
	coinhud: class extends self.ISpriteInstance {},
	coinsdisplay: class extends self.ISpriteFontInstance {},
	gemhud: class extends self.ISpriteInstance {},
	gemsdisplay: class extends self.ISpriteFontInstance {},
	crystalhud: class extends self.ISpriteInstance {},
	crystalsdisplay: class extends self.ISpriteFontInstance {},
	background: class extends self.ITiledBackgroundInstance {},
	minipopup: class extends self.ISpriteInstance {},
	shoparrow: class extends self.ISpriteInstance {},
	shop: class extends self.IWorldInstance {},
	catcoinupgradebase: class extends self.ISpriteInstance {},
	upgradelevel: class extends self.ISpriteFontInstance {},
	upgradecost: class extends self.ISpriteFontInstance {},
	upgradecosttype: class extends self.ISpriteFontInstance {},
	gemupgradebase: class extends self.ISpriteInstance {},
	crystalupgradebase: class extends self.ISpriteInstance {},
	pickaxeupgrade: class extends self.ISpriteInstance {},
	catminerupgrade: class extends self.ISpriteInstance {},
	dogworkerupgrade: class extends self.ISpriteInstance {},
	gemdrillerupgrade: class extends self.ISpriteInstance {},
	gemchancedisplay: class extends self.ISpriteFontInstance {},
	crystalchancedisplay: class extends self.ISpriteFontInstance {},
	catcoinsperclickdisplay: class extends self.ISpriteFontInstance {},
	catcoinsmultiplierdisplay: class extends self.ISpriteFontInstance {},
	gemmultiplierdisplay: class extends self.ISpriteFontInstance {},
	crystalmultiplierdisplay: class extends self.ISpriteFontInstance {},
	greenparticles: class extends self.IParticlesInstance {},
	greenstar: class extends self.ISpriteInstance {},
	purpleparticles: class extends self.IParticlesInstance {},
	purplestar: class extends self.ISpriteInstance {},
	crystaldrillerupgrade: class extends self.ISpriteInstance {},
	cattreatsicon: class extends self.ISpriteInstance {},
	rebirthmenubutton: class extends self.ISpriteInstance {},
	rebirthbackground: class extends self.ISpriteInstance {},
	awardbackground: class extends self.ITiledBackgroundInstance {},
	rebirthicon: class extends self.ISpriteInstance {},
	rebirthparticles: class extends self.IParticlesInstance {},
	rebirthstar: class extends self.ISpriteInstance {},
	awardtext: class extends self.ISpriteFontInstance {},
	rebirthcatcoincostdisplay: class extends self.ISpriteFontInstance {},
	hudicon: class extends self.ISpriteInstance {},
	rebirthgemcostdisplay: class extends self.ISpriteFontInstance {},
	rebirthcrystalcostdisplay: class extends self.ISpriteFontInstance {},
	rebirthbutton: class extends self.ISpriteInstance {},
	clickanywhere: class extends self.ISpriteFontInstance {},
	arrow: class extends self.ISpriteInstance {},
	whiteorb: class extends self.ISpriteInstance {},
	miniwhiteorb: class extends self.ISpriteInstance {},
	alert: class extends self.ISpriteFontInstance {},
	cattreatsshopbutton: class extends self.ISpriteInstance {},
	cattreatsshopbackground: class extends self.ITiledBackgroundInstance {},
	cattreatsdisplay: class extends self.ISpriteFontInstance {},
	cattreatsupgradebase: class extends self.ISpriteInstance {},
	catcoinmultiplierupgrade: class extends self.ISpriteInstance {},
	gemmultiplierupgrade: class extends self.ISpriteInstance {},
	crystalmultiplierupgrade: class extends self.ISpriteInstance {},
	pickaxeupgradearrow: class extends self.ISpriteInstance {},
	gempickaxeupgrade: class extends self.ISpriteInstance {},
	crystalpickaxeupgrade: class extends self.ISpriteInstance {},
	cattreatsfromrebirthsupgrade: class extends self.ISpriteInstance {},
	labmenubutton: class extends self.ISpriteInstance {},
	labbackground: class extends self.ITiledBackgroundInstance {},
	researchmenu: class extends self.IWorldInstance {},
	researchicon: class extends self.ISpriteInstance {},
	researchdisplay: class extends self.ISpriteFontInstance {},
	researchmenuarrow: class extends self.ISpriteInstance {},
	bigflask: class extends self.ISpriteInstance {},
	transferbutton: class extends self.ISpriteInstance {},
	catcoinresearchamountdisplay: class extends self.ISpriteFontInstance {},
	gemresearchamountdisplay: class extends self.ISpriteFontInstance {},
	crystalresearchamountdisplay: class extends self.ISpriteFontInstance {},
	researchbarback: class extends self.ISpriteInstance {},
	researchbar: class extends self.ISpriteInstance {},
	researchupgradebase: class extends self.ISpriteInstance {},
	rebirthcountdisplay: class extends self.ISpriteFontInstance {},
	Touch: class extends self.IInstance {},
	rebirthcattreatsrewarddisplay: class extends self.ISpriteFontInstance {},
	supergemdrillerupgrade: class extends self.ISpriteInstance {},
	holdclickupgrade: class extends self.ISpriteInstance {},
	supercrystaldrillerupgrade: class extends self.ISpriteInstance {},
	researchpickaxeupgrade: class extends self.ISpriteInstance {},
	gemfabricatorupgrade: class extends self.ISpriteInstance {},
	loadingbarback: class extends self.ISpriteInstance {},
	loadingbar: class extends self.ISpriteInstance {},
	loadingtext: class extends self.ISpriteFontInstance {},
	loadingpercentagetext: class extends self.ISpriteFontInstance {},
	loadingbackground: class extends self.ITiledBackgroundInstance {},
	diamondhud: class extends self.ISpriteInstance {},
	diamondchancedisplay: class extends self.ISpriteFontInstance {},
	diamondmultiplierdisplay: class extends self.ISpriteFontInstance {},
	diamonddisplay: class extends self.ISpriteFontInstance {},
	diamondupgradebase: class extends self.ISpriteInstance {},
	blueparticles: class extends self.IParticlesInstance {},
	bluestar: class extends self.ISpriteInstance {},
	diamondpickaxeupgrade: class extends self.ISpriteInstance {},
	rebirthdiamondcostdisplay: class extends self.ISpriteFontInstance {},
	diamondmultiplierupgrade: class extends self.ISpriteInstance {},
	minicatminer: class extends self.ISpriteInstance {},
	whitestar: class extends self.ISpriteInstance {},
	snowstorm: class extends self.IParticlesInstance {},
	disappearparticles: class extends self.IParticlesInstance {},
	minicatgemdriller: class extends self.ISpriteInstance {},
	minicatcrystaldriller: class extends self.ISpriteInstance {},
	tooltip: class extends self.IWorldInstance {},
	tooltiparrow: class extends self.ISpriteInstance {},
	diamondchanceupgrade: class extends self.ISpriteInstance {},
	superdiamondchanceupgrade: class extends self.ISpriteInstance {},
	descriptionText: class extends self.ISpriteFontInstance {},
	midground: class extends self.ITiledBackgroundInstance {},
	dogworker: class extends self.ISpriteInstance {},
	crystalrefineryupgrade: class extends self.ISpriteInstance {},
	kittenquarryupgrade: class extends self.ISpriteInstance {},
	kittenquarry: class extends self.ISpriteInstance {},
	pickaxemenubutton: class extends self.ISpriteInstance {},
	pickaxemenubackground: class extends self.ITiledBackgroundInstance {},
	pickaxedisplay: class extends self.ISpriteInstance {},
	pickaxeselectarrow: class extends self.ISpriteInstance {},
	pickaxematerialdisplay: class extends self.ISpriteFontInstance {},
	buypickaxebutton: class extends self.ISpriteInstance {},
	pickaxecosthud: class extends self.ISpriteInstance {},
	pickaxecostdisplay: class extends self.ISpriteFontInstance {},
	bigpickaxe: class extends self.ISpriteInstance {},
	researchspeedupgrade: class extends self.ISpriteInstance {},
	shippingicon: class extends self.ISpriteInstance {},
	shippingbackground: class extends self.ITiledBackgroundInstance {},
	aspectratiofixer: class extends self.ISpriteInstance {},
	viewcodebutton: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Upgrades: class extends self.ISpriteInstance {},
	CatcoinUpgrades: class extends self.ISpriteInstance {},
	GemUpgrades: class extends self.ISpriteInstance {},
	CrystalUpgrades: class extends self.ISpriteInstance {},
	UpgradeLabels: class extends self.ISpriteFontInstance {},
	Buttons: class extends self.ISpriteInstance {},
	CatTreatsUpgrades: class extends self.ISpriteInstance {},
	ResearchUpgrades: class extends self.ISpriteInstance {},
	DiamondUpgrades: class extends self.ISpriteInstance {}
}